const fs = require('fs');

const countries = [
  { code: 'ANY', name: 'Any Country / Любая страна', flag: '🌎' },
  { code: 'RU', name: 'Россия', flag: '🇷🇺' },
  { code: 'US', name: 'United States', flag: '🇺🇸' },
  { code: 'CN', name: '中国', flag: '🇨🇳' },
  { code: 'IN', name: 'भारत', flag: '🇮🇳' },
  { code: 'BR', name: 'Brasil', flag: '🇧🇷' },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩' },
  { code: 'PK', name: 'پاکستان', flag: '🇵🇰' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬' },
  { code: 'BD', name: 'বাংলাদেশ', flag: '🇧🇩' },
  { code: 'JP', name: '日本', flag: '🇯🇵' },
  { code: 'MX', name: 'México', flag: '🇲🇽' },
  { code: 'PH', name: 'Pilipinas', flag: '🇵🇭' },
  { code: 'ET', name: 'Ityopiya', flag: '🇪🇹' },
  { code: 'VN', name: 'Việt Nam', flag: '🇻🇳' },
  { code: 'EG', name: 'مصر', flag: '🇪🇬' },
  { code: 'DE', name: 'Deutschland', flag: '🇩🇪' },
  { code: 'IR', name: 'ایران', flag: '🇮🇷' },
  { code: 'TR', name: 'Türkiye', flag: '🇹🇷' },
  { code: 'CD', name: 'République démocratique du Congo', flag: '🇨🇩' },
  { code: 'FR', name: 'France', flag: '🇫🇷' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
  { code: 'TH', name: 'ประเทศไทย', flag: '🇹🇭' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦' },
  { code: 'IT', name: 'Italia', flag: '🇮🇹' },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿' },
  { code: 'MM', name: 'မြန်မာ', flag: '🇲🇲' },
  { code: 'KR', name: '대한민국', flag: '🇰🇷' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪' },
  { code: 'ES', name: 'España', flag: '🇪🇸' },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷' },
  { code: 'UA', name: 'Україна', flag: '🇺🇦' },
  { code: 'DZ', name: 'الجزائر', flag: '🇩🇿' },
  { code: 'SD', name: 'السودان', flag: '🇸🇩' },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬' },
  { code: 'IQ', name: 'العراق', flag: '🇮🇶' },
  { code: 'PL', name: 'Polska', flag: '🇵🇱' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦' },
  { code: 'MA', name: 'المغرب', flag: '🇲🇦' },
  { code: 'UZ', name: 'Oʻzbekiston', flag: '🇺🇿' },
  { code: 'SA', name: 'السعودية', flag: '🇸🇦' },
  { code: 'PE', name: 'Perú', flag: '🇵🇪' },
  { code: 'AF', name: 'افغانستان', flag: '🇦🇫' },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺' },
  { code: 'CI', name: 'Côte d\'Ivoire', flag: '🇨🇮' },
  { code: 'MD', name: 'Moldova', flag: '🇲🇩' },
  { code: 'BY', name: 'Беларусь', flag: '🇧🇾' },
  { code: 'KZ', name: 'Қазақстан', flag: '🇰🇿' },
  { code: 'IL', name: 'ישראל', flag: '🇮🇱' },
  { code: 'AE', name: 'الإمارات العربية المتحدة', flag: '🇦🇪' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬' },
  { code: 'SE', name: 'Sverige', flag: '🇸🇪' },
  { code: 'CH', name: 'Schweiz / Suisse / Svizzera', flag: '🇨🇭' },
  { code: 'NL', name: 'Nederland', flag: '🇳🇱' },
  { code: 'BE', name: 'België / Belgique', flag: '🇧🇪' },
  { code: 'AT', name: 'Österreich', flag: '🇦🇹' },
  { code: 'NO', name: 'Norge', flag: '🇳🇴' },
  { code: 'DK', name: 'Danmark', flag: '🇩🇰' },
  { code: 'FI', name: 'Suomi', flag: '🇫🇮' },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿' },
  { code: 'IE', name: 'Éire / Ireland', flag: '🇮🇪' },
  { code: 'CZ', name: 'Česko', flag: '🇨🇿' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹' },
  { code: 'GR', name: 'Ελλάδα', flag: '🇬🇷' },
  { code: 'RO', name: 'România', flag: '🇷🇴' },
  { code: 'AL', name: 'Shqipëria', flag: '🇦🇱' },
  { code: 'AD', name: 'Andorra', flag: '🇦🇩' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴' },
  { code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬' },
  { code: 'AM', name: 'Հայաստան', flag: '🇦🇲' },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸' },
  { code: 'BH', name: 'البحرين', flag: '🇧🇭' },
  { code: 'BB', name: 'Barbados', flag: '🇧🇧' },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿' },
  { code: 'BJ', name: 'Bénin', flag: '🇧🇯' },
  { code: 'BT', name: 'འབྲུག་ཡུལ་', flag: '🇧🇹' },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴' },
  { code: 'BA', name: 'Bosna i Hercegovina', flag: '🇧🇦' },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼' },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳' },
  { code: 'BG', name: 'България', flag: '🇧🇬' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'BI', name: 'Uburundi', flag: '🇧🇮' },
  { code: 'CV', name: 'Cabo Verde', flag: '🇨🇻' },
  { code: 'KH', name: 'កម្ពុជា', flag: '🇰🇭' },
  { code: 'CM', name: 'Cameroun', flag: '🇨🇲' },
  { code: 'CF', name: 'République centrafricaine', flag: '🇨🇫' },
  { code: 'TD', name: 'Tchad', flag: '🇹🇩' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷' },
  { code: 'HR', name: 'Hrvatska', flag: '🇭🇷' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺' },
  { code: 'CY', name: 'Κύπρος', flag: '🇨🇾' },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯' },
  { code: 'DM', name: 'Dominica', flag: '🇩🇲' },
  { code: 'DO', name: 'República Dominicana', flag: '🇩🇴' },
  { code: 'EC', name: 'Ecuador', flag: '🇪🇨' },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻' },
  { code: 'GQ', name: 'Guinea Ecuatorial', flag: '🇬🇶' },
  { code: 'ER', name: 'Ertra', flag: '🇪🇷' },
  { code: 'EE', name: 'Eesti', flag: '🇪🇪' },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿' },
  { code: 'FJ', name: 'Fiji', flag: '🇫🇯' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦' },
  { code: 'GM', name: 'Gambia', flag: '🇬🇲' },
  { code: 'GE', name: 'საქართველო', flag: '🇬🇪' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭' },
  { code: 'GD', name: 'Grenada', flag: '🇬🇩' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹' },
  { code: 'GN', name: 'Guinée', flag: '🇬🇳' },
  { code: 'GW', name: 'Guiné-Bissau', flag: '🇬🇼' },
  { code: 'GY', name: 'Guyana', flag: '🇬🇾' },
  { code: 'HT', name: 'Haïti', flag: '🇭🇹' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳' },
  { code: 'HU', name: 'Magyarország', flag: '🇭🇺' },
  { code: 'IS', name: 'Ísland', flag: '🇮🇸' },
  { code: 'JM', name: 'Jamaica', flag: '🇯🇲' },
  { code: 'JO', name: 'الأردن', flag: '🇯🇴' },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮' },
  { code: 'KW', name: 'الكويت', flag: '🇰🇼' },
  { code: 'KG', name: 'Кыргызстан', flag: '🇰🇬' },
  { code: 'LA', name: 'ປະເທດລາວ', flag: '🇱🇦' },
  { code: 'LV', name: 'Latvija', flag: '🇱🇻' },
  { code: 'LB', name: 'لبنان', flag: '🇱🇧' },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸' },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷' },
  { code: 'LY', name: 'ليبيا', flag: '🇱🇾' },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮' },
  { code: 'LT', name: 'Lietuva', flag: '🇱🇹' },
  { code: 'LU', name: 'Lëtzebuerg', flag: '🇱🇺' },
  { code: 'MG', name: 'Madagasikara', flag: '🇲🇬' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼' },
  { code: 'MV', name: 'ދިވެހިރާއްޖެ', flag: '🇲🇻' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱' },
  { code: 'MT', name: 'Malta', flag: '🇲🇹' },
  { code: 'MH', name: 'Marshall Islands', flag: '🇲🇭' },
  { code: 'MR', name: 'موريتانيا', flag: '🇲🇷' },
  { code: 'MU', name: 'Maurice', flag: '🇲🇺' },
  { code: 'FM', name: 'Micronesia', flag: '🇫🇲' },
  { code: 'MC', name: 'Monaco', flag: '🇲🇨' },
  { code: 'MN', name: 'Монгол Улс', flag: '🇲🇳' },
  { code: 'ME', name: 'Crna Gora', flag: '🇲🇪' },
  { code: 'MZ', name: 'Moçambique', flag: '🇲🇿' },
  { code: 'NA', name: 'Namibia', flag: '🇳🇦' },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷' },
  { code: 'NP', name: 'नेपाल', flag: '🇳🇵' },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪' },
  { code: 'KP', name: '조선민주주의인민공화국', flag: '🇰🇵' },
  { code: 'MK', name: 'Северна Македонија', flag: '🇲🇰' },
  { code: 'OM', name: 'عُمان', flag: '🇴🇲' },
  { code: 'PW', name: 'Palau', flag: '🇵🇼' },
  { code: 'PS', name: 'فلسطين', flag: '🇵🇸' },
  { code: 'PA', name: 'Panamá', flag: '🇵🇦' },
  { code: 'PG', name: 'Papua Niugini', flag: '🇵🇬' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾' },
  { code: 'QA', name: 'قطر', flag: '🇶🇦' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼' },
  { code: 'KN', name: 'Saint Kitts and Nevis', flag: '🇰🇳' },
  { code: 'LC', name: 'Saint Lucia', flag: '🇱🇨' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨' },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸' },
  { code: 'SM', name: 'San Marino', flag: '🇸🇲' },
  { code: 'ST', name: 'São Tomé e Príncipe', flag: '🇸🇹' },
  { code: 'SN', name: 'Sénégal', flag: '🇸🇳' },
  { code: 'RS', name: 'Србија', flag: '🇷🇸' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨' },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱' },
  { code: 'SK', name: 'Slovensko', flag: '🇸🇰' },
  { code: 'SI', name: 'Slovenija', flag: '🇸🇮' },
  { code: 'SB', name: 'Solomon Islands', flag: '🇸🇧' },
  { code: 'SO', name: 'Soomaaliya', flag: '🇸🇴' },
  { code: 'SS', name: 'South Sudan', flag: '🇸🇸' },
  { code: 'LK', name: 'ශ්‍රී ලංකාව', flag: '🇱🇰' },
  { code: 'SR', name: 'Suriname', flag: '🇸🇷' },
  { code: 'SY', name: 'سوريا', flag: '🇸🇾' },
  { code: 'TJ', name: 'Тоҷикистон', flag: '🇹🇯' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬' },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴' },
  { code: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹' },
  { code: 'TN', name: 'تونس', flag: '🇹🇳' },
  { code: 'TM', name: 'Türkmenistan', flag: '🇹🇲' },
  { code: 'TV', name: 'Tuvalu', flag: '🇹🇻' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾' },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺' },
  { code: 'YE', name: 'اليمن', flag: '🇾🇪' },
  { code: 'ZM', name: 'Zambia', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼' }
];

let contents = fs.readFileSync('src/constants.ts', 'utf8');
contents = contents.replace(/export const COUNTRIES: Country\[\] = \[[^]*?\];/, `export const COUNTRIES: Country[] = ${JSON.stringify(countries, null, 2)};`);
fs.writeFileSync('src/constants.ts', contents);
